wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  entity: mleigh
  offline: False
  id: null
  log_model: False
  project: ${project_name}
  name: ${network_name}
  save_dir: ${paths.full_path}

csv:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${paths.full_path}
  name: csv_logs
  version: null
  prefix: ""
  flush_logs_every_n_steps: 50