_target_: src.models.diffusion.DiffusionGenerator

time_embedding_dim: 64
loss_name: mae
ema_sync: 0.999

# How time information is injected into the UNet
cosine_config:
  min_value: 0
  max_value: 1
  frequency_scaling: exponential

# How quickly the noise takes over the image
diff_shedule_config:
  max_sr: 0.02
  min_sr: 0.95

# The configuration of the UNet
unet_config:
  min_size: 8
  attn_below: 16
  start_channels: 32
  max_channels: 256
  resnet_kwargs:
    act: silu
    nrm_groups: 32
  attn_kwargs:
    num_heads: 4
    nrm_groups: 32
  ctxt_embed_kwargs:
    hddn_dim: 128
    outp_dim: 128
    act_h: silu

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-4
  weight_decay: 1.0e-4

# Config dicts to pass to mattstools and pytorch lightning
sched_config:
  mattstools:
    name: warmup
    num_steps: 10000
  lightning:
    monitor: valid/noise_loss
    interval: step
    frequency: 1