_target_: src.models.diffusion.DiffusionGenerator

cosine_config:
  min_value: 0
  max_value: 1
  frequency_scaling: exponential

diff_shedule_config:
  max_sr: 0.02
  min_sr: 0.95

# How time information is injected into the UNet
time_embedding_dim: 64
time_embed_config:
  num_blocks: 2
  hddn_dim: 128
  outp_dim: 128

# The configuration of the UNet
unet_config:
  min_size: 8
  attn_below: 16
  start_channels: 32
  max_channels: 128
  resnet_kwargs:
    act: lrlu
    nrm_groups: 32
  attn_kwargs:
    num_heads: 4
    nrm_groups: 32

# Passed to mattstools get_loss_fn
loss_name: mae

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5.0e-4
  weight_decay: 1.0e-4

# Config dicts to pass to mattstools and pytorch lightning
sched_conf:
  mattstools:
    name: warmup
    num_steps: 5000
  lightning:
    monitor: valid/noise_loss
    interval: step
    frequency: 1