upscale_factor: 8
gan_mode: lsgan
grad_clip: 10
optim_dict:
  name: adam
  lr: 1.0e-4
sched_dict:
  name: none

unet_kwargs:
  min_size: 4
  attn_after: 3
  start_channels: 32
  max_channels: 128
  resnet_kwargs:
    act: lrlu
    drp: 0.1
    nrm_groups: 32
  attn_kwargs:
    num_heads: 4
    nrm_groups: 32

disc_kwargs:
  outp_size: 16
  start_channels: 32
  max_channels: 64
  resnet_kwargs:
    act: lrlu
    drp: 0.1
    nrm_groups: 32


