_target_: src.models.unetsr.UNetSuperResolution

upscale_factor: 8

unet_kwargs:
  min_size: 8
  attn_below: 16
  start_channels: 32
  max_channels: 128
  resnet_kwargs:
    act: lrlu
    drp: 0.1
    nrm_groups: 32
  attn_kwargs:
    num_heads: 4
    nrm_groups: 32
  ctxt_embed_kwargs:
    hddn_dim: 64
    outp_dim: 64
    act_h: lrlu

loss_name: mse

# Full configuration for the model optimizer
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5.0e-4

# Config dicts to pass to mattstools and pytorch lightning
sched_conf:
  mattstools:
    name: warmup
    num_steps: 1024
  lightning:
    monitor: valid/loss
    interval: step
    frequency: 1
